# Font configuration
[font]
size = 12.0

[font.normal]
family = "RecMonoLinear Nerd Font"
style = "Regular"

# Cursor configuration
[cursor]
blink_interval = 0

[cursor.style]
shape = "Block"
blinking = "Never"

# Colors (Gruvbox Dark theme)
[colors.primary]
foreground = "#ebdbb2"
background = "#32302f"

[colors.cursor]
cursor = "#ebdbb2"
text = "#32302f"

[colors.selection]
foreground = "#32302f"
background = "#ebdbb2"

# Normal colors
[colors.normal]
black = "#32302f"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

# Bright colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# Window configuration
[window]
opacity = 0.97
blur = true
# decorations = "None"

[window.padding]
x = 5
y = 5

# Shell integration
[selection]
save_to_clipboard = true

# URL detection
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
